# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4623ebfd3aca8cca77bc935c54f18e704a495c8df0dbe4128d9bcd01655b3d8060baea421ccc98a60d467c019859e0ec3723d86845058c3aade3e0249dd0e3c8

test:
  secret_key_base: 01a30d6655a5e30d457d847e05625ec4b215a465b2cdd80b1a9bb880995d6f9b5be3d227ff1ec8aae2e922f19c5a92b2f6c83739a184f17d57ec5867997efc26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
